server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/securitydb?useUnicode=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  # Thymeleaf 配置
  # 关闭缓存
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: "classpath*:mapper/*.xml"
  type-aliases-package: com.wangguangwu.springsecurity02.entity

logging:
  level:
    com:
      wangguangwu:
        springsecurity02: debug